[project]
name = "cross-link"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.21",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]

[tool.ruff.lint]
extend-select = ["I", "TYP", "UP"]
