name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - uses: ts-graphviz/setup-graphviz@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: sd

      - run: uv sync
      - run: make
        shell: bash

      - name: Prepare README.md for pandoc
        run: |
          sd '^# ([^\r\n]+)\r?\n' '$1.\n' README.md
      - name: Build index.html
        uses: docker://pandoc/core:3
        with:
          args: >-
            README.md
            --from gfm
            --standalone
            --output build/index.html
            --metadata title="Links across Typst Documentation"

      - uses: actions/upload-pages-artifact@v4
        with:
          path: build/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
